In [23]:
import pandas as pd
df = pd.read_csv('data/processed/indexed_price.csv')

In [24]:
df.head()

,SISTEMA,TARIFA,CIA,MES,FEE,P1,P2,P3,P4,P5,P6,diferencia
0,BALEARES,2.0TD,ACCIONA,2023-06-01,Cierzo,0.212767,0.165975,0.142781,0.0,0.0,0.0,224 days 10:32:07.896139
1,BALEARES,2.0TD,ACCIONA,2023-05-01,Cierzo,0.190597,0.143704,0.120055,0.0,0.0,0.0,255 days 10:32:07.896139
2,BALEARES,2.0TD,ACCIONA,2023-04-01,Cierzo,0.190032,0.143135,0.119475,0.0,0.0,0.0,285 days 10:32:07.896139
3,BALEARES,2.0TD,ACCIONA,2023-03-01,Cierzo,0.208748,0.161937,0.138661,0.0,0.0,0.0,316 days 10:32:07.896139
4,BALEARES,2.0TD,ACCIONA,2023-02-01,Cierzo,0.260442,0.213867,0.191651,0.0,0.0,0.0,344 days 10:32:07.896139

In [20]:
from datetime import datetime

df['MES'] = pd.to_datetime(df['MES'])

In [22]:
# df.drop(columns=['Unnamed: 0.1',	'Unnamed: 0'],inplace=True)
# df.to_csv('data/processed/indexed_price.csv',index=False)

In [14]:
fecha_actual = datetime.now()

df['diferencia'] = (fecha_actual - df['MES']).abs() # diferencia entre cada fecha 'MES' y la fecha actual


condicion = (df['SISTEMA'] == 'PENINSULA') & (df['TARIFA'] == '2.0TD') # filtrar para obtener las filas más cercanas por CIA y con SISTEMA y TARIFA específicos
filas_mas_cercanas = df[condicion].groupby(['SISTEMA', 'TARIFA', 'CIA']).apply(lambda x: x[x['diferencia'] == x['diferencia'].min()])

filas_mas_cercanas = filas_mas_cercanas.drop('diferencia', axis=1).reset_index(drop=True)

print(filas_mas_cercanas)

    Unnamed: 0.1  Unnamed: 0    SISTEMA TARIFA      CIA        MES  \
0           4304        4304  PENINSULA  2.0TD  ACCIONA 2023-07-01
1           4323        4323  PENINSULA  2.0TD  ACCIONA 2023-07-01
2           4342        4342  PENINSULA  2.0TD  ACCIONA 2023-07-01
3           4361        4361  PENINSULA  2.0TD  ACCIONA 2023-07-01
4           4380        4380  PENINSULA  2.0TD  ACCIONA 2023-07-01
5           4407        4407  PENINSULA  2.0TD  ACCIONA 2023-07-01
6           4444        4444  PENINSULA  2.0TD  ACCIONA 2023-07-01
7           9489        9489  PENINSULA  2.0TD      AEQ 2023-09-01
8           9490        9490  PENINSULA  2.0TD      AEQ 2023-09-01
9           9491        9491  PENINSULA  2.0TD      AEQ 2023-09-01
10          9492        9492  PENINSULA  2.0TD      AEQ 2023-09-01
11          9493        9493  PENINSULA  2.0TD      AEQ 2023-09-01
12          9494        9494  PENINSULA  2.0TD      AEQ 2023-09-01
13          9495        9495  PENINSULA  2.0TD      AEQ 2023-09-01
14          9496        9496  PENINSULA  2.0TD      AEQ 2023-09-01
15          9603        9603  PENINSULA  2.0TD  CANDELA 2023-09-01
16          9604        9604  PENINSULA  2.0TD  CANDELA 2023-09-01
17          9605        9605  PENINSULA  2.0TD  CANDELA 2023-09-01
18          9606        9606  PENINSULA  2.0TD  CANDELA 2023-09-01
19          9607        9607  PENINSULA  2.0TD  CANDELA 2023-09-01
20          9608        9608  PENINSULA  2.0TD  CANDELA 2023-09-01
21          9609        9609  PENINSULA  2.0TD  CANDELA 2023-09-01
22          9610        9610  PENINSULA  2.0TD  CANDELA 2023-09-01
23          9611        9611  PENINSULA  2.0TD  CANDELA 2023-09-01
24          9612        9612  PENINSULA  2.0TD  CANDELA 2023-09-01
25          9613        9613  PENINSULA  2.0TD  CANDELA 2023-09-01
26          4808        4808  PENINSULA  2.0TD    ELEIA 2022-12-01
27          4820        4820  PENINSULA  2.0TD    ELEIA 2022-12-01
28          4832        4832  PENINSULA  2.0TD    ELEIA 2022-12-01
29          4844        4844  PENINSULA  2.0TD    ELEIA 2022-12-01
30          4856        4856  PENINSULA  2.0TD    ELEIA 2022-12-01
31          4868        4868  PENINSULA  2.0TD    ELEIA 2022-12-01
32          4880        4880  PENINSULA  2.0TD    ELEIA 2022-12-01
33          4892        4892  PENINSULA  2.0TD    ELEIA 2022-12-01
34          9084        9084  PENINSULA  2.0TD   FACTOR 2023-08-01
35          9085        9085  PENINSULA  2.0TD   FACTOR 2023-08-01
36          9086        9086  PENINSULA  2.0TD   FACTOR 2023-08-01
37          9087        9087  PENINSULA  2.0TD   FACTOR 2023-08-01
38          9088        9088  PENINSULA  2.0TD   FACTOR 2023-08-01
39          9089        9089  PENINSULA  2.0TD   FACTOR 2023-08-01
40          9090        9090  PENINSULA  2.0TD   FACTOR 2023-08-01
41          9091        9091  PENINSULA  2.0TD   FACTOR 2023-08-01
42          9092        9092  PENINSULA  2.0TD   FACTOR 2023-08-01
43          9093        9093  PENINSULA  2.0TD   FACTOR 2023-08-01
44          9094        9094  PENINSULA  2.0TD   FACTOR 2023-08-01
45          9095        9095  PENINSULA  2.0TD   FACTOR 2023-08-01
46          9096        9096  PENINSULA  2.0TD   FACTOR 2023-08-01
47          5138        5138  PENINSULA  2.0TD     GANA 2022-12-01
48          9381        9381  PENINSULA  2.0TD    IGNIS 2023-08-01
49          9382        9382  PENINSULA  2.0TD    IGNIS 2023-08-01
50          9383        9383  PENINSULA  2.0TD    IGNIS 2023-08-01
51          9384        9384  PENINSULA  2.0TD    IGNIS 2023-08-01
52          9385        9385  PENINSULA  2.0TD    IGNIS 2023-08-01
53          9386        9386  PENINSULA  2.0TD    IGNIS 2023-08-01
54          9387        9387  PENINSULA  2.0TD    IGNIS 2023-08-01
55          9388        9388  PENINSULA  2.0TD    IGNIS 2023-08-01
56          9389        9389  PENINSULA  2.0TD    IGNIS 2023-08-01
57          5318        5318  PENINSULA  2.0TD      MAX 2023-07-01
58          5325        5325  PENINSULA  2.0TD      MAX 2023-07-01
59          5332        5332  PENINSULA  2.0TD      MAX 2023-07-01
60          5339        5339  PENINSULA  2.0TD      MAX 2023-07-01
61          5346        5346  PENINSULA  2.0TD      MAX 2023-07-01
62          5353        5353  PENINSULA  2.0TD      MAX 2023-07-01
63          5360        5360  PENINSULA  2.0TD      MAX 2023-07-01
64          5367        5367  PENINSULA  2.0TD      MAX 2023-07-01
65          5374        5374  PENINSULA  2.0TD      MAX 2023-07-01
66          5381        5381  PENINSULA  2.0TD      MAX 2023-07-01
67          5388        5388  PENINSULA  2.0TD      MAX 2023-07-01
68          5395        5395  PENINSULA  2.0TD      MAX 2023-07-01

                 FEE        P1        P2        P3   P4   P5   P6
0             Cierzo  0.209144  0.162335  0.139067  0.0  0.0  0.0
1            Levante  0.228429  0.181620  0.158352  0.0  0.0  0.0
2           Levante+  0.228429  0.181620  0.158352  0.0  0.0  0.0
3           Poniente  0.218279  0.171470  0.148202  0.0  0.0  0.0
4          Poniente+  0.218279  0.171470  0.148202  0.0  0.0  0.0
5         Tramontana  0.211174  0.164365  0.141097  0.0  0.0  0.0
6        Tramontana+  0.211174  0.164365  0.141097  0.0  0.0  0.0
7                  3  0.233793  0.176134  0.144558  0.0  0.0  0.0
8                  6  0.236793  0.179134  0.147558  0.0  0.0  0.0
9                  8  0.238793  0.181134  0.149558  0.0  0.0  0.0
10                10  0.240793  0.183134  0.151558  0.0  0.0  0.0
11                15  0.245793  0.188134  0.156558  0.0  0.0  0.0
12                20  0.250793  0.193134  0.161558  0.0  0.0  0.0
13                25  0.255793  0.198134  0.166558  0.0  0.0  0.0
14                30  0.260793  0.203134  0.171558  0.0  0.0  0.0
15      01 / Bi0,035  0.266444  0.209453  0.175862  0.0  0.0  0.0
16       02 / Bi0,03  0.261444  0.204453  0.170862  0.0  0.0  0.0
17      03 / Bi0,025  0.256444  0.199453  0.165862  0.0  0.0  0.0
18       04 / Bi0,02  0.251444  0.194453  0.160862  0.0  0.0  0.0
19      05 / Bi0,018  0.249444  0.192453  0.158862  0.0  0.0  0.0
20      06 / Bi0,015  0.246444  0.189453  0.155862  0.0  0.0  0.0
21      07 / Bi0,012  0.243444  0.186453  0.152862  0.0  0.0  0.0
22       08 / Bi0,01  0.241444  0.184453  0.150862  0.0  0.0  0.0
23      09 / Bi0,008  0.239444  0.182453  0.148862  0.0  0.0  0.0
24      10 / Bi0,006  0.237444  0.180453  0.146862  0.0  0.0  0.0
25      11 / Bi0,003  0.234444  0.177453  0.143862  0.0  0.0  0.0
26              TDE0  0.229856  0.182507  0.161680  0.0  0.0  0.0
27              TDE1  0.225896  0.178548  0.157721  0.0  0.0  0.0
28              TDE2  0.220719  0.173370  0.152543  0.0  0.0  0.0
29              TDE3  0.216658  0.169309  0.148482  0.0  0.0  0.0
30              TEE0  0.229856  0.182507  0.161680  0.0  0.0  0.0
31              TEE1  0.225896  0.178548  0.157721  0.0  0.0  0.0
32              TEE2  0.220719  0.173370  0.152543  0.0  0.0  0.0
33              TEE3  0.216658  0.169309  0.148482  0.0  0.0  0.0
34                 4  0.207887  0.156710  0.126418  0.0  0.0  0.0
35                 6  0.209887  0.158710  0.128418  0.0  0.0  0.0
36               7.5  0.211387  0.160210  0.129918  0.0  0.0  0.0
37               8.5  0.212387  0.161210  0.130918  0.0  0.0  0.0
38               9.5  0.213387  0.162210  0.131918  0.0  0.0  0.0
39              11.5  0.215387  0.164210  0.133918  0.0  0.0  0.0
40              13.5  0.217387  0.166210  0.135918  0.0  0.0  0.0
41              15.5  0.219387  0.168210  0.137918  0.0  0.0  0.0
42              17.5  0.221387  0.170210  0.139918  0.0  0.0  0.0
43              19.5  0.223387  0.172210  0.141918  0.0  0.0  0.0
44              21.5  0.225387  0.174210  0.143918  0.0  0.0  0.0
45              23.5  0.227387  0.176210  0.145918  0.0  0.0  0.0
46              25.5  0.229387  0.178210  0.147918  0.0  0.0  0.0
47                 -  0.220339  0.157463  0.136512  0.0  0.0  0.0
48   30 MARE PLUS 1   0.242365  0.190414  0.158846  0.0  0.0  0.0
49   25 MARE PLUS 2   0.237365  0.185414  0.153846  0.0  0.0  0.0
50   20 MARE PLUS 3   0.232365  0.180414  0.148846  0.0  0.0  0.0
51    15 MARE ZEN 1   0.227365  0.175414  0.143846  0.0  0.0  0.0
52    10 MARE ZEN 2   0.222365  0.170414  0.138846  0.0  0.0  0.0
53     8 MARE ZEN 3   0.220365  0.168414  0.136846  0.0  0.0  0.0
54     6 MARE KIT 1   0.218365  0.166414  0.134846  0.0  0.0  0.0
55     4 MARE KIT 2   0.216365  0.164414  0.132846  0.0  0.0  0.0
56    2,5 MARE KIT 3  0.214865  0.162914  0.131346  0.0  0.0  0.0
57                10       NaN       NaN       NaN  NaN  NaN  NaN
58                12       NaN       NaN       NaN  NaN  NaN  NaN
59                15       NaN       NaN       NaN  NaN  NaN  NaN
60                18       NaN       NaN       NaN  NaN  NaN  NaN
61                20       NaN       NaN       NaN  NaN  NaN  NaN
62                25       NaN       NaN       NaN  NaN  NaN  NaN
63                 3       NaN       NaN       NaN  NaN  NaN  NaN
64                30       NaN       NaN       NaN  NaN  NaN  NaN
65                35       NaN       NaN       NaN  NaN  NaN  NaN
66                40       NaN       NaN       NaN  NaN  NaN  NaN
67                 6       NaN       NaN       NaN  NaN  NaN  NaN
68                 8       NaN       NaN       NaN  NaN  NaN  NaN

In [5]:
pd.set_option('display.max_rows', None)

In [6]:
filas_mas_cercanas.head()

,Unnamed: 0.1,Unnamed: 0,SISTEMA,TARIFA,CIA,MES,FEE,P1,P2,P3,P4,P5,P6
0,4304,4304,PENINSULA,2.0TD,ACCIONA,2023-07-01,Cierzo,0.209144,0.162335,0.139067,0.0,0.0,0.0
1,4323,4323,PENINSULA,2.0TD,ACCIONA,2023-07-01,Levante,0.228429,0.181620,0.158352,0.0,0.0,0.0
2,4342,4342,PENINSULA,2.0TD,ACCIONA,2023-07-01,Levante+,0.228429,0.181620,0.158352,0.0,0.0,0.0
3,4361,4361,PENINSULA,2.0TD,ACCIONA,2023-07-01,Poniente,0.218279,0.171470,0.148202,0.0,0.0,0.0
4,4380,4380,PENINSULA,2.0TD,ACCIONA,2023-07-01,Poniente+,0.218279,0.171470,0.148202,0.0,0.0,0.0

In [7]:
filas_mas_cercanas.dropna(axis=0,inplace=True)

In [8]:
index_power = pd.read_csv('data/processed/indexed_price_power.csv')

In [9]:
# condiciones para filtrar (sería con el desplegable)
condiciones_sistema_tarifa = (index_power['SISTEMA'] == 'PENINSULA') & (index_power['TARIFA'] == '2.0TD') & (index_power['PRODUCTO'] == 'INDEXADO')

condiciones_cias = index_power['CIA'].isin(['ACCIONA', 'AEQ', 'CANDELA', 'FACTOR', 'IGNIS', 'MAX'])

index_power_filtrado = index_power[condiciones_sistema_tarifa & condiciones_cias] # aplicar el filtro

index_power_filtrado.head()

,SISTEMA,CIA,PRODUCTO,PRODUCTO_CIA,TARIFA,P1,P2,P3,P4,P5,P6
94,PENINSULA,ACCIONA,INDEXADO,CIERZO,2.0TD,0.088121,0.019570,0.0,0.0,0.0,0.0
98,PENINSULA,ACCIONA,INDEXADO,LEVANTE+,2.0TD,0.082641,0.014091,0.0,0.0,0.0,0.0
102,PENINSULA,ACCIONA,INDEXADO,LEVANTE,2.0TD,0.071682,0.003132,0.0,0.0,0.0,0.0
106,PENINSULA,ACCIONA,INDEXADO,PONIENTE+,2.0TD,0.077162,0.008611,0.0,0.0,0.0,0.0
110,PENINSULA,ACCIONA,INDEXADO,PONIENTE,2.0TD,0.071682,0.003132,0.0,0.0,0.0,0.0

In [10]:
filas_mas_cercanas['FEE'] = filas_mas_cercanas['FEE'].str.upper()

In [36]:
# funciones de cálculo importes
def calcular_energia(cons_mens_P1,cons_mens_P2,cons_mens_P3, precio_mens_P1,precio_mens_P2,precio_mens_P3,descuento):
    # sumatorio_cons_mens=cons_mens_P1+cons_mens_P2+cons_mens_P3
    precio_P1_descuento= precio_mens_P1 * (1-descuento) #€
    precio_P2_descuento= precio_mens_P2 * (1-descuento)
    precio_P3_descuento= precio_mens_P3 * (1-descuento)
    
    #añadir P4,P5,P6 como None/0/1

    total_pago_P1_energia= cons_mens_P1 * precio_P1_descuento #€
    total_pago_P2_energia= cons_mens_P2 * precio_P2_descuento
    total_pago_P3_energia= cons_mens_P3 * precio_P3_descuento

    sumatorio_total_pago_energia = total_pago_P1_energia + total_pago_P2_energia + total_pago_P3_energia
    return sumatorio_total_pago_energia

def calcular_potencia(potencia_contratada_P1,potencia_contratada_P2,dias,precio_potencia_dia_P1,precio_potencia_dia_P2):
    total_pago_P1_potencia= dias * precio_potencia_dia_P1 * potencia_contratada_P1
    total_pago_P2_potencia= dias * precio_potencia_dia_P2 * potencia_contratada_P2
    sumatorio_total_pago_potencia = total_pago_P1_potencia + total_pago_P2_potencia
    return sumatorio_total_pago_potencia
    
def calcular_total_factura(sumatorio_total_pago_energia,sumatorio_total_pago_potencia,impuesto_electrico,otros,IVA):
    bi_IVA= (sumatorio_total_pago_energia + sumatorio_total_pago_potencia
         +impuesto_electrico + otros)
    importe_total_factura_mens= bi_IVA * (1+IVA)
    return importe_total_factura_mens

In [46]:
def encontrar_opcion_mas_barata(df_energia, df_potencia):
    opciones = []

    df_combinado = pd.merge(df_energia, df_potencia, on='CIA',suffixes=["_E","_P"])
    df_combinado.dropna(axis=0,inplace=True)

    for index,row in df_combinado.iterrows():
        cons_mens_P1, cons_mens_P2, cons_mens_P3 = 74, 83, 168 #CAMBIAR A INPUT DE LA FACTURA
        potencia_contratada_P1, potencia_contratada_P2 = 3.45, 3.45 #CAMBIAR A INPUT DE LA FACTURA
        precio_mens_P1, precio_mens_P2, precio_mens_P3 = row['P1_E'], row['P2_E'], row['P3_E']
        precio_potencia_dia_P1, precio_potencia_dia_P2 = row['P1_P'], row['P2_P']
        descuento = 0.02  # CAMBIAR A INPUT DE LA FACTURA
        dias = 33 # CAMBIAR A INPUT DE LA FACTURA
        
        sumatorio_total_pago_energia = calcular_energia(cons_mens_P1, cons_mens_P2, cons_mens_P3, precio_mens_P1, precio_mens_P2, precio_mens_P3, descuento)
        sumatorio_total_pago_potencia = calcular_potencia(potencia_contratada_P1, potencia_contratada_P2, dias, precio_potencia_dia_P1, precio_potencia_dia_P2)
        impuesto_electrico, otros, IVA = 5, 2, 0.21  # CAMBIAR A INPUT DE LA FACTURA

        # print(sumatorio_total_pago_energia,sumatorio_total_pago_potencia)

        importe_total_factura_mens = calcular_total_factura(sumatorio_total_pago_energia, sumatorio_total_pago_potencia, impuesto_electrico, otros, IVA)

        opciones.append({
            'CIA': row['CIA'],
            'FEE': row['FEE'],
            'PRODUCTO_CIA': row['PRODUCTO_CIA'],
            'CostoTotal': importe_total_factura_mens
        })

    # Opción más barata para cada compañía
    df_opciones = pd.DataFrame(opciones)
    idx_opcion_mas_barata = df_opciones['CostoTotal'].idxmin()
    
    opcion_barata=df_opciones.iloc[idx_opcion_mas_barata]

    opciones_mas_baratas = df_opciones.nsmallest(5, 'CostoTotal')
    ahorro=importe_total_factura_mens-opcion_barata['CostoTotal']

    return 'Precio actual:',importe_total_factura_mens,'Opción más barata:',opcion_barata,'Ahorro:',ahorro, "Opciones más baratas:", opciones_mas_baratas

In [47]:
encontrar_opcion_mas_barata(filas_mas_cercanas,index_power_filtrado)

('Precio actual:',
 81.97393527580948,
 'Opción más barata:',
 CIA                         FACTOR
 FEE                              4
 PRODUCTO_CIA    DOMESTICO_POOLDBOE
 CostoTotal               77.406676
 Name: 128, dtype: object,
 'Ahorro:',
 4.56725971939305,
 'Opciones más baratas:',
         CIA  FEE         PRODUCTO_CIA  CostoTotal
 128  FACTOR    4   DOMESTICO_POOLDBOE   77.406676
 130  FACTOR    4  NEGOCIO_POOLNAHORRO   77.406676
 135  FACTOR    6   DOMESTICO_POOLDBOE   78.177446
 137  FACTOR    6  NEGOCIO_POOLNAHORRO   78.177446
 142  FACTOR  7.5   DOMESTICO_POOLDBOE   78.755523)