In [3]:
import pandas as pd
df = pd.read_csv('data/processed/indexed_price.csv')

In [51]:
df.head()

,SISTEMA,TARIFA,CIA,MES,FEE,P1,P2,P3,P4,P5,P6,diferencia
0,BALEARES,2.0TD,ACCIONA,2023-06-01,Cierzo,0.212767,0.165975,0.142781,0.0,0.0,0.0,224 days 08:25:31.711181
1,BALEARES,2.0TD,ACCIONA,2023-05-01,Cierzo,0.190597,0.143704,0.120055,0.0,0.0,0.0,255 days 08:25:31.711181
2,BALEARES,2.0TD,ACCIONA,2023-04-01,Cierzo,0.190032,0.143135,0.119475,0.0,0.0,0.0,285 days 08:25:31.711181
3,BALEARES,2.0TD,ACCIONA,2023-03-01,Cierzo,0.208748,0.161937,0.138661,0.0,0.0,0.0,316 days 08:25:31.711181
4,BALEARES,2.0TD,ACCIONA,2023-02-01,Cierzo,0.260442,0.213867,0.191651,0.0,0.0,0.0,344 days 08:25:31.711181

In [52]:
from datetime import datetime

df['MES'] = pd.to_datetime(df['MES'])

df.to_csv('data/processed/indexed_price.csv')

In [53]:
fecha_actual = datetime.now()

df['diferencia'] = (fecha_actual - df['MES']).abs() # diferencia entre cada fecha 'MES' y la fecha actual


condicion = (df['SISTEMA'] == 'PENINSULA') & (df['TARIFA'] == '2.0TD') # filtrar para obtener las filas más cercanas por CIA y con SISTEMA y TARIFA específicos
filas_mas_cercanas = df[condicion].groupby(['SISTEMA', 'TARIFA', 'CIA']).apply(lambda x: x[x['diferencia'] == x['diferencia'].min()])

filas_mas_cercanas = filas_mas_cercanas.drop('diferencia', axis=1).reset_index(drop=True)

print(filas_mas_cercanas)

      SISTEMA TARIFA      CIA        MES               FEE        P1  \
0   PENINSULA  2.0TD  ACCIONA 2023-07-01            Cierzo  0.209144
1   PENINSULA  2.0TD  ACCIONA 2023-07-01           Levante  0.228429
2   PENINSULA  2.0TD  ACCIONA 2023-07-01          Levante+  0.228429
3   PENINSULA  2.0TD  ACCIONA 2023-07-01          Poniente  0.218279
4   PENINSULA  2.0TD  ACCIONA 2023-07-01         Poniente+  0.218279
5   PENINSULA  2.0TD  ACCIONA 2023-07-01        Tramontana  0.211174
6   PENINSULA  2.0TD  ACCIONA 2023-07-01       Tramontana+  0.211174
7   PENINSULA  2.0TD      AEQ 2023-09-01                 3  0.233793
8   PENINSULA  2.0TD      AEQ 2023-09-01                 6  0.236793
9   PENINSULA  2.0TD      AEQ 2023-09-01                 8  0.238793
10  PENINSULA  2.0TD      AEQ 2023-09-01                10  0.240793
11  PENINSULA  2.0TD      AEQ 2023-09-01                15  0.245793
12  PENINSULA  2.0TD      AEQ 2023-09-01                20  0.250793
13  PENINSULA  2.0TD      AEQ 2023-09-01                25  0.255793
14  PENINSULA  2.0TD      AEQ 2023-09-01                30  0.260793
15  PENINSULA  2.0TD  CANDELA 2023-09-01      01 / Bi0,035  0.266444
16  PENINSULA  2.0TD  CANDELA 2023-09-01       02 / Bi0,03  0.261444
17  PENINSULA  2.0TD  CANDELA 2023-09-01      03 / Bi0,025  0.256444
18  PENINSULA  2.0TD  CANDELA 2023-09-01       04 / Bi0,02  0.251444
19  PENINSULA  2.0TD  CANDELA 2023-09-01      05 / Bi0,018  0.249444
20  PENINSULA  2.0TD  CANDELA 2023-09-01      06 / Bi0,015  0.246444
21  PENINSULA  2.0TD  CANDELA 2023-09-01      07 / Bi0,012  0.243444
22  PENINSULA  2.0TD  CANDELA 2023-09-01       08 / Bi0,01  0.241444
23  PENINSULA  2.0TD  CANDELA 2023-09-01      09 / Bi0,008  0.239444
24  PENINSULA  2.0TD  CANDELA 2023-09-01      10 / Bi0,006  0.237444
25  PENINSULA  2.0TD  CANDELA 2023-09-01      11 / Bi0,003  0.234444
26  PENINSULA  2.0TD    ELEIA 2022-12-01              TDE0  0.229856
27  PENINSULA  2.0TD    ELEIA 2022-12-01              TDE1  0.225896
28  PENINSULA  2.0TD    ELEIA 2022-12-01              TDE2  0.220719
29  PENINSULA  2.0TD    ELEIA 2022-12-01              TDE3  0.216658
30  PENINSULA  2.0TD    ELEIA 2022-12-01              TEE0  0.229856
31  PENINSULA  2.0TD    ELEIA 2022-12-01              TEE1  0.225896
32  PENINSULA  2.0TD    ELEIA 2022-12-01              TEE2  0.220719
33  PENINSULA  2.0TD    ELEIA 2022-12-01              TEE3  0.216658
34  PENINSULA  2.0TD   FACTOR 2023-08-01                 4  0.207887
35  PENINSULA  2.0TD   FACTOR 2023-08-01                 6  0.209887
36  PENINSULA  2.0TD   FACTOR 2023-08-01               7.5  0.211387
37  PENINSULA  2.0TD   FACTOR 2023-08-01               8.5  0.212387
38  PENINSULA  2.0TD   FACTOR 2023-08-01               9.5  0.213387
39  PENINSULA  2.0TD   FACTOR 2023-08-01              11.5  0.215387
40  PENINSULA  2.0TD   FACTOR 2023-08-01              13.5  0.217387
41  PENINSULA  2.0TD   FACTOR 2023-08-01              15.5  0.219387
42  PENINSULA  2.0TD   FACTOR 2023-08-01              17.5  0.221387
43  PENINSULA  2.0TD   FACTOR 2023-08-01              19.5  0.223387
44  PENINSULA  2.0TD   FACTOR 2023-08-01              21.5  0.225387
45  PENINSULA  2.0TD   FACTOR 2023-08-01              23.5  0.227387
46  PENINSULA  2.0TD   FACTOR 2023-08-01              25.5  0.229387
47  PENINSULA  2.0TD     GANA 2022-12-01                 -  0.220339
48  PENINSULA  2.0TD    IGNIS 2023-08-01   30 MARE PLUS 1   0.242365
49  PENINSULA  2.0TD    IGNIS 2023-08-01   25 MARE PLUS 2   0.237365
50  PENINSULA  2.0TD    IGNIS 2023-08-01   20 MARE PLUS 3   0.232365
51  PENINSULA  2.0TD    IGNIS 2023-08-01    15 MARE ZEN 1   0.227365
52  PENINSULA  2.0TD    IGNIS 2023-08-01    10 MARE ZEN 2   0.222365
53  PENINSULA  2.0TD    IGNIS 2023-08-01     8 MARE ZEN 3   0.220365
54  PENINSULA  2.0TD    IGNIS 2023-08-01     6 MARE KIT 1   0.218365
55  PENINSULA  2.0TD    IGNIS 2023-08-01     4 MARE KIT 2   0.216365
56  PENINSULA  2.0TD    IGNIS 2023-08-01    2,5 MARE KIT 3  0.214865
57  PENINSULA  2.0TD      MAX 2023-07-01                10       NaN
58  PENINSULA  2.0TD      MAX 2023-07-01                12       NaN
59  PENINSULA  2.0TD      MAX 2023-07-01                15       NaN
60  PENINSULA  2.0TD      MAX 2023-07-01                18       NaN
61  PENINSULA  2.0TD      MAX 2023-07-01                20       NaN
62  PENINSULA  2.0TD      MAX 2023-07-01                25       NaN
63  PENINSULA  2.0TD      MAX 2023-07-01                 3       NaN
64  PENINSULA  2.0TD      MAX 2023-07-01                30       NaN
65  PENINSULA  2.0TD      MAX 2023-07-01                35       NaN
66  PENINSULA  2.0TD      MAX 2023-07-01                40       NaN
67  PENINSULA  2.0TD      MAX 2023-07-01                 6       NaN
68  PENINSULA  2.0TD      MAX 2023-07-01                 8       NaN

          P2        P3   P4   P5   P6
0   0.162335  0.139067  0.0  0.0  0.0
1   0.181620  0.158352  0.0  0.0  0.0
2   0.181620  0.158352  0.0  0.0  0.0
3   0.171470  0.148202  0.0  0.0  0.0
4   0.171470  0.148202  0.0  0.0  0.0
5   0.164365  0.141097  0.0  0.0  0.0
6   0.164365  0.141097  0.0  0.0  0.0
7   0.176134  0.144558  0.0  0.0  0.0
8   0.179134  0.147558  0.0  0.0  0.0
9   0.181134  0.149558  0.0  0.0  0.0
10  0.183134  0.151558  0.0  0.0  0.0
11  0.188134  0.156558  0.0  0.0  0.0
12  0.193134  0.161558  0.0  0.0  0.0
13  0.198134  0.166558  0.0  0.0  0.0
14  0.203134  0.171558  0.0  0.0  0.0
15  0.209453  0.175862  0.0  0.0  0.0
16  0.204453  0.170862  0.0  0.0  0.0
17  0.199453  0.165862  0.0  0.0  0.0
18  0.194453  0.160862  0.0  0.0  0.0
19  0.192453  0.158862  0.0  0.0  0.0
20  0.189453  0.155862  0.0  0.0  0.0
21  0.186453  0.152862  0.0  0.0  0.0
22  0.184453  0.150862  0.0  0.0  0.0
23  0.182453  0.148862  0.0  0.0  0.0
24  0.180453  0.146862  0.0  0.0  0.0
25  0.177453  0.143862  0.0  0.0  0.0
26  0.182507  0.161680  0.0  0.0  0.0
27  0.178548  0.157721  0.0  0.0  0.0
28  0.173370  0.152543  0.0  0.0  0.0
29  0.169309  0.148482  0.0  0.0  0.0
30  0.182507  0.161680  0.0  0.0  0.0
31  0.178548  0.157721  0.0  0.0  0.0
32  0.173370  0.152543  0.0  0.0  0.0
33  0.169309  0.148482  0.0  0.0  0.0
34  0.156710  0.126418  0.0  0.0  0.0
35  0.158710  0.128418  0.0  0.0  0.0
36  0.160210  0.129918  0.0  0.0  0.0
37  0.161210  0.130918  0.0  0.0  0.0
38  0.162210  0.131918  0.0  0.0  0.0
39  0.164210  0.133918  0.0  0.0  0.0
40  0.166210  0.135918  0.0  0.0  0.0
41  0.168210  0.137918  0.0  0.0  0.0
42  0.170210  0.139918  0.0  0.0  0.0
43  0.172210  0.141918  0.0  0.0  0.0
44  0.174210  0.143918  0.0  0.0  0.0
45  0.176210  0.145918  0.0  0.0  0.0
46  0.178210  0.147918  0.0  0.0  0.0
47  0.157463  0.136512  0.0  0.0  0.0
48  0.190414  0.158846  0.0  0.0  0.0
49  0.185414  0.153846  0.0  0.0  0.0
50  0.180414  0.148846  0.0  0.0  0.0
51  0.175414  0.143846  0.0  0.0  0.0
52  0.170414  0.138846  0.0  0.0  0.0
53  0.168414  0.136846  0.0  0.0  0.0
54  0.166414  0.134846  0.0  0.0  0.0
55  0.164414  0.132846  0.0  0.0  0.0
56  0.162914  0.131346  0.0  0.0  0.0
57       NaN       NaN  NaN  NaN  NaN
58       NaN       NaN  NaN  NaN  NaN
59       NaN       NaN  NaN  NaN  NaN
60       NaN       NaN  NaN  NaN  NaN
61       NaN       NaN  NaN  NaN  NaN
62       NaN       NaN  NaN  NaN  NaN
63       NaN       NaN  NaN  NaN  NaN
64       NaN       NaN  NaN  NaN  NaN
65       NaN       NaN  NaN  NaN  NaN
66       NaN       NaN  NaN  NaN  NaN
67       NaN       NaN  NaN  NaN  NaN
68       NaN       NaN  NaN  NaN  NaN

In [5]:
pd.set_option('display.max_rows', None)

In [6]:
filas_mas_cercanas.head()

,SISTEMA,TARIFA,CIA,MES,FEE,P1,P2,P3,P4,P5,P6
0,PENINSULA,2.0TD,ACCIONA,2023-07-01,Cierzo,0.209144,0.162335,0.139067,0.0,0.0,0.0
1,PENINSULA,2.0TD,ACCIONA,2023-07-01,Levante,0.228429,0.181620,0.158352,0.0,0.0,0.0
2,PENINSULA,2.0TD,ACCIONA,2023-07-01,Levante+,0.228429,0.181620,0.158352,0.0,0.0,0.0
3,PENINSULA,2.0TD,ACCIONA,2023-07-01,Poniente,0.218279,0.171470,0.148202,0.0,0.0,0.0
4,PENINSULA,2.0TD,ACCIONA,2023-07-01,Poniente+,0.218279,0.171470,0.148202,0.0,0.0,0.0

In [20]:
index_power = pd.read_csv('data/processed/indexed_price_power.csv')

In [27]:
# condiciones para filtrar (sería con el desplegable)
condiciones_sistema_tarifa = (index_power['SISTEMA'] == 'PENINSULA') & (index_power['TARIFA'] == '2.0TD') & (index_power['PRODUCTO'] == 'INDEXADO')

condiciones_cias = index_power['CIA'].isin(['ACCIONA', 'AEQ', 'CANDELA', 'FACTOR', 'IGNIS', 'MAX'])

index_power_filtrado = index_power[condiciones_sistema_tarifa & condiciones_cias] # aplicar el filtro

index_power_filtrado.head()

,SISTEMA,CIA,PRODUCTO,PRODUCTO_CIA,TARIFA,P1,P2,P3,P4,P5,P6
94,PENINSULA,ACCIONA,INDEXADO,CIERZO,2.0TD,0.088121,0.019570,0.0,0.0,0.0,0.0
98,PENINSULA,ACCIONA,INDEXADO,LEVANTE+,2.0TD,0.082641,0.014091,0.0,0.0,0.0,0.0
102,PENINSULA,ACCIONA,INDEXADO,LEVANTE,2.0TD,0.071682,0.003132,0.0,0.0,0.0,0.0
106,PENINSULA,ACCIONA,INDEXADO,PONIENTE+,2.0TD,0.077162,0.008611,0.0,0.0,0.0,0.0
110,PENINSULA,ACCIONA,INDEXADO,PONIENTE,2.0TD,0.071682,0.003132,0.0,0.0,0.0,0.0

In [28]:
filas_mas_cercanas['FEE'] = filas_mas_cercanas['FEE'].str.upper()

In [49]:
# funciones de cálculo importes
def calcular_energia(cons_mens_P1,cons_mens_P2,cons_mens_P3, precio_mens_P1,precio_mens_P2,precio_mens_P3,descuento):
    # sumatorio_cons_mens=cons_mens_P1+cons_mens_P2+cons_mens_P3
    precio_P1_descuento= precio_mens_P1 * (1-descuento) #€
    precio_P2_descuento= precio_mens_P2 * (1-descuento)
    precio_P3_descuento= precio_mens_P3 * (1-descuento)

    total_pago_P1_energia= cons_mens_P1 * precio_P1_descuento #€
    total_pago_P2_energia= cons_mens_P2 * precio_P2_descuento
    total_pago_P3_energia= cons_mens_P3 * precio_P3_descuento

    sumatorio_total_pago_energia = total_pago_P1_energia + total_pago_P2_energia + total_pago_P3_energia
    return sumatorio_total_pago_energia

def calcular_potencia(potencia_contratada_P1,potencia_contratada_P2,dias,precio_potencia_dia_P1,precio_potencia_dia_P2):
    total_pago_P1_potencia= dias * precio_potencia_dia_P1 * potencia_contratada_P1
    total_pago_P2_potencia= dias * precio_potencia_dia_P2 * potencia_contratada_P2
    sumatorio_total_pago_potencia = total_pago_P1_potencia + total_pago_P2_potencia
    return sumatorio_total_pago_potencia

def calcular_total_factura(sumatorio_total_pago_energia,sumatorio_total_pago_potencia,impuesto_electrico,otros,IVA):
    bi_IVA= (sumatorio_total_pago_energia + sumatorio_total_pago_potencia
         +impuesto_electrico + otros)
    importe_total_factura_mens= bi_IVA * (1+IVA)
    return importe_total_factura_mens

def encontrar_opcion_mas_barata(df_energia, df_potencia):
    opciones = []

    df_combinado = pd.merge(df_energia, df_potencia, on='CIA',suffixes=["_E","_P"])

    for index,row in df_combinado.iterrows():
        cons_mens_P1, cons_mens_P2, cons_mens_P3 = 74, 83, 168 #CAMBIAR A INPUT DE LA FACTURA
        potencia_contratada_P1, potencia_contratada_P2 = 3.45, 3.45 #CAMBIAR A INPUT DE LA FACTURA
        precio_mens_P1, precio_mens_P2, precio_mens_P3 = row['P1_E'], row['P2_E'], row['P3_E']
        precio_potencia_dia_P1, precio_potencia_dia_P2 = row['P1_P'], row['P2_P']
        descuento = 0.02  # CAMBIAR A INPUT DE LA FACTURA
        dias = 33 # CAMBIAR A INPUT DE LA FACTURA
        
        sumatorio_total_pago_energia = calcular_energia(cons_mens_P1, cons_mens_P2, cons_mens_P3, precio_mens_P1, precio_mens_P2, precio_mens_P3, descuento)
        sumatorio_total_pago_potencia = calcular_potencia(potencia_contratada_P1, potencia_contratada_P2, dias, precio_potencia_dia_P1, precio_potencia_dia_P2)
        impuesto_electrico, otros, IVA = 5, 2, 0.21  # CAMBIAR A INPUT DE LA FACTURA

        importe_total_factura_mens = calcular_total_factura(sumatorio_total_pago_energia, sumatorio_total_pago_potencia, impuesto_electrico, otros, IVA)

        opciones.append({
            'CIA': row['CIA'],
            'FEE': row['FEE'],
            'PRODUCTO_CIA': row['PRODUCTO_CIA'],
            'CostoTotal': importe_total_factura_mens
        })

    # Opción más barata para cada compañía
    df_opciones = pd.DataFrame(opciones)
    idx_opcion_mas_barata = df_opciones['CostoTotal'].idxmin()
    
    opcion_barata=df_opciones.iloc[idx_opcion_mas_barata]

    opciones_mas_baratas = df_opciones.nsmallest(5, 'CostoTotal')
    
    return 'Opción más barata:',opcion_barata, "Opciones más baratas:", opciones_mas_baratas

In [50]:
encontrar_opcion_mas_barata(filas_mas_cercanas,index_power_filtrado)

('Opción más barata:',
 CIA                         FACTOR
 FEE                              4
 PRODUCTO_CIA    DOMESTICO_POOLDBOE
 CostoTotal               77.406676
 Name: 128, dtype: object,
 'Opciones más baratas:',
         CIA  FEE         PRODUCTO_CIA  CostoTotal
 128  FACTOR    4   DOMESTICO_POOLDBOE   77.406676
 130  FACTOR    4  NEGOCIO_POOLNAHORRO   77.406676
 135  FACTOR    6   DOMESTICO_POOLDBOE   78.177446
 137  FACTOR    6  NEGOCIO_POOLNAHORRO   78.177446
 142  FACTOR  7.5   DOMESTICO_POOLDBOE   78.755523)